version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb1
    restart: always
    ports:
      - "27017:27017"
    # Environment o'chirildi - authentication'siz
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      # Authentication'siz
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data: 

# services:
#   mongodb:
#     image: mongo
#     container_name: mongodb1
#     restart: always
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: admin
#       MONGO_INITDB_ROOT_PASSWORD: admin123
#       MONGO_INITDB_DATABASE: terabayt
#     volumes:
#       - ./mongo_data:/data/db

#   mongo-express:
#     image: mongo-express
#     container_name: mongo-express
#     restart: always
#     ports:
#       - "8081:8081"
#     environment:
#       ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
#       ME_CONFIG_MONGODB_SERVER: mongodb
#       ME_CONFIG_BASICAUTH: "false"   # <-- Sign In butunlay o‘chirildi
